config/routes.rb
Rails.application.routes.draw do

  root  'static_pages#home'
  delete '/logout',       to: 'sessions#destroy'

  resources :fps, except: [:index, :new, :create] do
    collection do 
      get  'login',  to: 'sessions#fp_new'
      post 'login',  to: 'sessions#fp_create'
      get  'signup', to: 'fps#new'
      post 'signup', to: 'fps#create'
    end
    resources :fp_reservable_times, only: [:new, :create, :destroy]
  end

  resources :users, except: [:index, :new, :create] do
    collection do 
      get  'login',  to: 'sessions#user_new'
      post 'login',  to: 'sessions#user_create'
      get  'signup', to: 'users#new'
      post 'signup', to: 'users#create'
    end
    resources :reservations, only: [:new, :create, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
  include ModelConstants

  has_many :reservations,  dependent: :destroy
  has_many :reserving_fps, through: :reservations, source: :fp

  before_validation { email.downcase! } # 今回はemailの大文字・小文字を区別しない
  
  has_secure_password
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def show
    @user_reservations = @user.reservations.show_order.page(params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user @user
      flash[:success] = "ユーザの新規登録に成功しました"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "更新しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = "退会しました"
    else
      flash[:danger]  = "退会できませんでした"
    end
    redirect_to root_url
  end

  private

    def user_params
      params
      .require(:user)
      .permit(
        :name,
        :email,
        :password,
        :password_confirmation
      )
    end

    # beforeアクション

    # ユーザーのログインを確認する
    def logged_in_user
      unless logged_in_user?
        flash[:danger] = "権限がありません"
        redirect_to root_url
      end
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user ||= User.find(params[:id])
      unless current_user?(@user)
        flash[:danger] = "権限がありません"
        redirect_to root_url
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title      , 'User edit') %>
<% provide(:url        ,  user_path) %>
<% provide(:button_text, '更新する') %>
<h1>ユーザ情報の更新</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "layouts/form", object: @user %>
    <%= link_to "退会", user_path(@user), method: :delete,
        data: {confirm: "本当に退会してもいいですか？（復元できません）"} %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title      , 'ユーザ登録') %>
<% provide(:url        ,  signup_users_path) %>
<% provide(:button_text, 'ユーザ登録') %>
<h1>ユーザ登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render  "layouts/form", object: @user %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-success table-responsive">
      <div class="panel-heading"><b>予約した相談</b></div>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>FP名前</th><th>日付</th><th>時間</th><th>アクション</th>
          </tr>
        </thead>
        <tbody>
          <% @user_reservations.each do |f| %>
            <tr>
              <td><%= f.fp.name %></td>
              <td><%= f.reserved_on.strftime("%Y/%m/%d")%></td>
              <td><%= f.consultation_period %></td>
              <td><%= link_to  "予約取り消し", user_reservation_path(@user, f),
                  method: :delete, data: {confirm: "予約取り消してもよろしいですか？"} %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @user_reservations %>
  </div>
</div>