config/routes.rb
Rails.application.routes.draw do

  root  'static_pages#home'
  delete '/logout',       to: 'sessions#destroy'

  resources :fps, except: [:index, :new, :create] do
    collection do 
      get  'login',  to: 'sessions#fp_new'
      post 'login',  to: 'sessions#fp_create'
      get  'signup', to: 'fps#new'
      post 'signup', to: 'fps#create'
    end
    resources :fp_reservable_times, only: [:new, :create, :destroy]
  end

  resources :users, except: [:index, :new, :create] do
    collection do 
      get  'login',  to: 'sessions#user_new'
      post 'login',  to: 'sessions#user_create'
      get  'signup', to: 'users#new'
      post 'signup', to: 'users#create'
    end
    resources :reservations, only: [:new, :create, :destroy]
  end

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  include ModelConstants

  belongs_to :user
  belongs_to :fp

  scope :show_order, -> { order(reserved_on: :asc) }

  validates :fp_id,       presence: true
  validates :user_id,     presence: true
  validates :reserved_on, presence: true

  def finish_datetime
    reserved_on + CONSULTING_DURATION
  end

  # ビュー用。日をまたぐ場合は考慮にいれていない
  def consultation_period
    reserved_on.strftime("%H:%M") + " ~ " + finish_datetime.strftime("%H:%M")
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :destroy]
  before_action :correct_user,   only: [:new, :create, :destroy]

  def new
    @fps = Fp.all.includes(:fp_reservable_times).page(params[:id]) # N+1対策
  end

  def create
    reserved_on = FpReservableTime.find(params[:reservable_id]).reservable_on
    FpReservableTime.find(params[:reservable_id]).destroy
    reservation = Reservation.new(fp_id:       params[:fp_id],
                                  user_id:     params[:user_id],
                                  reserved_on: reserved_on)
    if reservation.save
      flash[:success] = "予約完了しました"
      redirect_to new_user_reservation_path
    else
      render 'new'
    end
  end

  def destroy
    reservation = Reservation.find(params[:id])
    if FpReservableTime.create(
      fp_id:         reservation.fp.id,
      reservable_on: reservation.reserved_on)
      reservation.destroy
      flash[:success] = "予約削除しました"
    else
      flash[:danger]  = "予約削除できませんでした"
    end
    redirect_to @user
  end

  private
    # beforeアクション

    # Userのログインを確認する
    def logged_in_user
      unless logged_in_user?
        flash[:danger] = "権限がありません"
        redirect_to root_url
      end
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user ||= User.find(params[:user_id])
      unless current_user?(@user)
        flash[:danger] = "権限がありません"
        redirect_to root_url
      end
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/new.html.erb
<% provide(:title, current_user.name) %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-info table-responsive">
      <div class="panel-heading"><b>予約</b></div>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>名前</th><th>日付</th><th>時間</th><th>アクション</th>
          </tr>
        </thead>
        <tbody>
          <% @fps.each do |fp| %>
            <% fp.fp_reservable_times.each do |reservable_time| %>
              <tr>
                <td><%= fp.name %></td>
                <td><%= reservable_time.reservable_on.strftime("%Y/%m/%d") %></td>
                <td><%= reservable_time.consultation_period %></td>
                <td><%= link_to  "予約する", user_reservations_path(@user,
                      params: { reservable_id: reservable_time.id, fp_id: fp.id } ),
                      method: :post, 
                      data: {confirm: "#{reservable_time.consultation_period}で予約しますか？"} 
                    %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @fps %>
  </div>
</div>