config/routes.rb
Rails.application.routes.draw do

  root  'static_pages#home'
  delete '/logout',       to: 'sessions#destroy'

  resources :fps, except: [:index, :new, :create] do
    collection do 
      get  'login',  to: 'sessions#fp_new'
      post 'login',  to: 'sessions#fp_create'
      get  'signup', to: 'fps#new'
      post 'signup', to: 'fps#create'
    end
    resources :fp_reservable_times, only: [:new, :create, :destroy]
  end

  resources :users, except: [:index, :new, :create] do
    collection do 
      get  'login',  to: 'sessions#user_new'
      post 'login',  to: 'sessions#user_create'
      get  'signup', to: 'users#new'
      post 'signup', to: 'users#create'
    end
    resources :reservations, only: [:new, :create, :destroy]
  end

end

app/models/fp.rb
class Fp < ApplicationRecord
  include ModelConstants

  has_many :reservations,        dependent: :destroy
  has_many :fp_reservable_times, dependent: :destroy
  has_many :reserved_users, through: :reservations, source: :user

  before_validation { email.downcase! } # 今回はemailの大文字・小文字を区別しない
  
  has_secure_password
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/controllers/fps_controller.rb
class FpsController < ApplicationController
  before_action :logged_in_fp, only: [:show, :edit, :update, :destroy]
  before_action :correct_fp,   only: [:show, :edit, :update, :destroy]

  def new
    @fp = Fp.new
  end

  def show
    @fp_reservable_times = @fp.fp_reservable_times.show_order.page(params[:reservable_page])
    @fp_reservations     = @fp.reservations.show_order.page(params[:reservation_page])
  end

  def create
    @fp = Fp.new(fp_params)
    if @fp.save
      log_in_fp @fp
      flash[:success] = "FPの新規登録に成功しました"
      redirect_to @fp
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @fp.update_attributes(fp_params)
      flash[:success] = "更新しました"
      redirect_to @fp
    else
      render 'edit'
    end
  end

  def destroy
    if @fp.destroy
      flash[:success] = "退会しました"
    else
      flash[:danger]  = "退会に失敗しました"
    end
    redirect_to root_url
  end

  private

    def fp_params
      params
      .require(:fp)
      .permit(
        :name,
        :email,
        :password,
        :password_confirmation
      )
    end

    # beforeアクション

    # FPのログインを確認する
    def logged_in_fp
      unless logged_in_fp?
        flash[:danger] = "権限がありません"
        redirect_to root_url
      end
    end

    # 正しいユーザーかどうか確認
    def correct_fp
      @fp ||= Fp.find(params[:id])
      unless current_fp?(@fp)
        flash[:danger] = "権限がありません"
        redirect_to root_url
      end
    end
end

app/helpers/fps_helper.rb
module FpsHelper
end

app/views/fps/edit.html.erb
<% provide(:title      , 'Fp edit') %>
<% provide(:url        ,  fp_path) %>
<% provide(:button_text, '更新する') %>
<h1>FP情報の更新</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render  "layouts/form", object: @fp %>
    <%= link_to "退会", fp_path(@fp), method: :delete,
        data: { confirm: "本当に退会してもいいですか？（復元できません）"} %>
  </div>
</div>

app/views/fps/new.html.erb
<% provide(:title      , 'FP登録') %>
<% provide(:url        ,  signup_fps_path) %>
<% provide(:button_text, 'FP登録') %>
<h1>FP 登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "layouts/form", object: @fp %>
  </div>
</div>

app/views/fps/show.html.erb
<% provide(:title, @fp.name) %>
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-info table-responsive">
      <div class="panel-heading"><b>予約受付中</b></div>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>日付</th><th>時間</th><th>アクション</th>
          </tr>
        </thead>
        <tbody>
          <% @fp_reservable_times.each do |f| %>
            <tr>
              <td><%= f.reservable_on.strftime("%Y/%m/%d") %></td>
              <td><%= f.consultation_period %></td>
              <td><%= link_to  "取り消し",  fp_fp_reservable_time_path(@fp, f),
                  method: :delete, data: {confirm: "予約受付を取り消してもよろしいですか？"} %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @fp_reservable_times, param_name: 'reservable_page'  %>
  </div>
  <div class="col-md-6">
    <div class="panel panel-success table-responsive">
      <div class="panel-heading"><b>予約済</b></div>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>日付</th><th>時間</th><th>氏名</th>
          </tr>
        </thead>
        <tbody>
          <% @fp_reservations.each do |f| %>
            <tr>
              <td><%= f.reserved_on.strftime("%Y/%m/%d")%></td><td><%= f.consultation_period %></td><td><%= f.user.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @fp_reservations, param_name: 'reservation_page' %>
  </div>
</div>