config/routes.rb
Rails.application.routes.draw do

  root  'static_pages#home'
  delete '/logout',       to: 'sessions#destroy'

  resources :fps, except: [:index, :new, :create] do
    collection do 
      get  'login',  to: 'sessions#fp_new'
      post 'login',  to: 'sessions#fp_create'
      get  'signup', to: 'fps#new'
      post 'signup', to: 'fps#create'
    end
    resources :fp_reservable_times, only: [:new, :create, :destroy]
  end

  resources :users, except: [:index, :new, :create] do
    collection do 
      get  'login',  to: 'sessions#user_new'
      post 'login',  to: 'sessions#user_create'
      get  'signup', to: 'users#new'
      post 'signup', to: 'users#create'
    end
    resources :reservations, only: [:new, :create, :destroy]
  end

end

app/views/layouts/_form.html.erb
<%= form_for(object, url: yield(:url)) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "FP予約", root_path, id: "logo" %>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <nav>
      <ul id="navbar" class="nav navbar-nav navbar-right navbar-collapse collapse">
        <li><%= link_to "ホーム", root_path %></li>
        <% if logged_in? %>
          <% if logged_in_user? %>
            <li><%= link_to "予約", new_user_reservation_path(current_user) %></li>
            <li><%= link_to "編集", edit_user_path(current_user) %></li>
            <li><%= link_to "マイページ", current_user %></li>
          <% elsif logged_in_fp? %>
            <li><%= link_to "マイページ", current_fp %></li>
            <li><%= link_to "編集", edit_fp_path(current_fp) %></li>
            <li><%= link_to "予約", new_fp_fp_reservable_time_path(current_fp) %></li>
          <% end %>
          <li>
            <%= link_to "ログアウト", logout_path,
              method: :delete,
              data: {confirm: "ログアウトしますか？"}
            %>
          </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              ログイン <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "ユーザ", login_users_path %></li>
              <li class="divider"></li>
              <li><%= link_to "FP", login_fps_path %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
                               

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_signup_form.html.erb
<%= form_for(object, url: yield(:url)) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <meta name="viewport" content="width=device-width" >
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>